version: '3.3'
services:
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lefoot
    ports:
      - '5432:5432'
    volumes: 
      - ./PGDATA:/var/lib/postgresql/data